Thread 1 killed on uncaught exception Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| merged common ancestors
Called from Thread.create.(fun) in file "thread.ml", line 47, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/5.1
[thread 2] caught Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| merged common ancestors
Called from Thread.create.(fun) in file "thread.ml", line 47, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/5.1
Thread 2 killed on uncaught exception Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| merged common ancestors
Called from Thread.create.(fun) in file "thread.ml", line 47, characters 8-14
=======
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/5.1
Thread 2 uncaught exception handler raised Uncaught_exception_handler.UncaughtHandlerExn
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-17
<<<<<<< HEAD
Called from Thread.create.(fun) in file "thread.ml", line 60, characters 10-41
[thread 3] caught Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 51, characters 8-14
||||||| merged common ancestors
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-26
Called from Thread.create.(fun) in file "thread.ml", line 53, characters 10-41
=======
Called from Thread.create.(fun) in file "thread.ml", line 57, characters 10-41
[thread 3] caught Uncaught_exception_handler.CallbackExn
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/5.1
